server:
    port: 8081

spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: test
        password: test
        url: jdbc:mysql://localhost:3306/testDB?serverTimezone=UTC
    jpa:
        open-in-view: false